# Generated by Django 3.1.4 on 2020-12-16 18:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, verbose_name='Place')),
                ('placeId', models.PositiveIntegerField(max_length=200, unique=True)),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('long_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Широта и Долгота')),
            ],
            options={
                'ordering': ['title', 'placeId'],
            },
        ),
        migrations.CreateModel(
            name='PlaceGeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='PlaceGeo')),
                ('placeId', models.CharField(max_length=200, unique=True)),
                ('detailsUrl', models.TextField(blank=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['title', 'placeId'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('number', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Позиция')),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='places.place')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
