# Generated by Django 3.1.4 on 2020-12-06 16:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.FloatField(blank=True, default=0, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name=(models.FloatField(blank=True, default=0, verbose_name='Latitude'), models.FloatField(blank=True, default=0, verbose_name='Longitude'))),
        ),
    ]
