# Generated by Django 3.1.7 on 2021-02-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20210212_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='places.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='place',
            name='detailsUrl',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
